### ISSUE TITLE
Adding Docker Compose bits to the documentation?

### ISSUE THREAD

**Issue by k8gg** [imTHAI/docker-pixelserv-tls#5]
Hi - If we want to do Docker Compose instead to install this thing, would something like this work? 
```
version: "0.9"
services:
  pixelserv-tls:
    image: imthai/pixelserv-tls
    container_name: pixelserv-tls
    restart: always
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/pixelserv:/var/cache/pixelserv
```
Am I missing anything?
